usage_text = """
Usage... The Flashcard Project (TFP) is a software application to make, manage, and view flashcards on a desktop. The native Windows interface and size-adjustable frame makes it convenient when using with other applications displayed. This is useful when studying a computer language so you can switch to a code editor or interpreter for testing and practice.

Cards can be categorized with tags and you can save your card decks. The files can be shared for use by anyone with a TFP application.

You can edit, add, and delete cards while you are studying. If there is a card you do not want to see again, click the Archive button. The deck can be reset at any time to return the status of all archived card to active. Otherwise, the deck will be automatically reset once all cards are viewed.

TFP provides a way for multiple people to contribute when generating a card deck. The software can export the card data to a human-readable YAML file. These files can be then be imported to TFP to allow multiple people to contribute to a deck by offering cards edits and additions. In fact, it can import multiple card decks that were generated by the TFP application. The imported cards can be saved to a consolidated deck file.

Use TFP application to help with learning for any subject. If you are an instructor, you might want to have your students download the application. They could be tasked with producing their own flashcards and submit them as card files. These files can then be imported and consolidated into a single file to distribute as a learning aid. 

Adding or deleting cards form a card deck does not change the index number of existing cards in the deck. For instance, you might delete some cards from a desk. If you add or import a new card, they may be assigned to indexes of deleted cards, but index numbers of the other cards will not have changed.
"""

about_text = """
About... The Flashcard Project (TFP) is a software application to make, manage, and view flashcards on a desktop. The native Windows interface and size-adjustable frame makes it convenient when using with other applications displayed. This is useful when studying a computer language so you can switch to a code editor or interpreter for testing and practice.

Cards can be categorized with tags and you can save your card decks. The files can be shared for use by anyone with a TFP application.

You can edit, add, and delete cards while you are studying. If there is a card you do not want to see again, click the Archive button. The deck can be reset at any time to return the status of all archived card to active. Otherwise, the deck will be automatically reset once all cards are viewed.

TFP provides a way for multiple people to contribute when generating a card deck. The software can export the card data to a human-readable YAML file. These files can be then be imported to TFP to allow multiple people to contribute to a deck by offering cards edits and additions. In fact, it can import multiple card decks that were generated by the TFP application. The imported cards can be saved to a consolidated deck file.

Use TFP application to help with learning for any subject. If you are an instructor, you might want to have your students download the application. They could be tasked with producing their own flashcards and submit them as card files. These files can then be imported and consolidated into a single file to distribute as a learning aid. 

Adding or deleting cards form a card deck does not change the index number of existing cards in the deck. For instance, you might delete some cards from a desk. If you add or import a new card, they may be assigned to indexes of deleted cards, but index numbers of the other cards will not have changed.
"""
